--- 
env: 
  - DJANGO_VERSION=1.8.2
ignore: 
  - "*.md"
install: 
  - "pip install -r requirements.txt"
language: python
python: 
  - "3.6"
  - "3.7"
  - "3.8"
script: 
  - "python manage.py runserver"
